#ifndef detector_marCCD_h
#define detector_marCCD_h

#include "detector.h"
#include "ccd_chips.h"


/* These should evenually be dynamically changeable depending on which chip is in use */
/*
------#ifdef CCD_CHIP_SERIAL_PREPIXELS
------#undef CCD_CHIP_SERIAL_PREPIXELS
------#undef CCD_CHIP_SERIAL_IMAGEPIXELS
------#undef CCD_CHIP_SERIAL_POSTPIXELS
------#undef CCD_CHIP_SERIAL_TOTALPIXELS
------#undef CCD_CHIP_PARALLEL_PREPIXELS
------#undef CCD_CHIP_PARALLEL_IMAGEPIXELS
------#undef CCD_CHIP_PARALLEL_POSTPIXELS
------#undef CCD_CHIP_PARALLEL_TOTALPIXELS
------#endif
------#define CCD_CHIP_SERIAL_PREPIXELS	SI424A_CCD_CHIP_SERIAL_PREPIXELS	
------#define CCD_CHIP_SERIAL_IMAGEPIXELS	SI424A_CCD_CHIP_SERIAL_IMAGEPIXELS	
------#define CCD_CHIP_SERIAL_POSTPIXELS	SI424A_CCD_CHIP_SERIAL_POSTPIXELS	
------#define CCD_CHIP_SERIAL_TOTALPIXELS	SI424A_CCD_CHIP_SERIAL_TOTALPIXELS	
------#define CCD_CHIP_PARALLEL_PREPIXELS	SI424A_CCD_CHIP_PARALLEL_PREPIXELS	
------#define CCD_CHIP_PARALLEL_IMAGEPIXELS	SI424A_CCD_CHIP_PARALLEL_IMAGEPIXELS	
------#define CCD_CHIP_PARALLEL_POSTPIXELS	SI424A_CCD_CHIP_PARALLEL_POSTPIXELS	
------#define CCD_CHIP_PARALLEL_TOTALPIXELS	SI424A_CCD_CHIP_PARALLEL_TOTALPIXELS	
------
------#define DETECTOR_MAR0_NFAST		CCD_CHIP_SERIAL_IMAGEPIXELS
------#define DETECTOR_MAR0_NSLOW		CCD_CHIP_PARALLEL_IMAGEPIXELS
------#define DETECTOR_MAR0_IMAGESIZE 	(DETECTOR_MAR0_NFAST * DETECTOR_MAR0_NFAST)
*/


/* This will depend on how many readouts there are and/or how many are in use */
#define DETECTOR_MAR0_NFASTDETECTORS 	1
#define DETECTOR_MAR0_NSLOWDETECTORS 	1
#define DETECTOR_MAR0_NDETECTORS 	(DETECTOR_MAR0_NSLOWDETECTORS*DETECTOR_MAR0_NFASTDETECTORS)

#define DETECTOR_MAR0_READSIZE		8192
#define DETECTOR_MAR0_DMA_BUFFER_SIZE	8192


/* A Function for each type of detector */
extern detector_functions *get_detector_marCCD(void);
void get_driver_version_marCCD(char *driver_version);


#endif /* detector_marCCD_h */
